#Jamie Hawthorne
#Used to contain commands to compile projects

TARGET:
	g++ main.cpp Semaphore.cpp -O -pthread

DEBUG: DEBUGFLAGS = -DDEBUG
DEBUG: ALL

#this is customary and just deletes all .o files
CLEAN:
	rm *.o